spring:
  application:
    name: snakegame-api
  datasource:
    url: jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?user=postgres.qqqoekklvuwmzvfoldmx&password=SnakeGame2026
    driver-class-name: org.postgresql.Driver
  hikari:
    maximum-pool-size: 2
    minimum-idle: 1

